### PR TITLE
Add zendesk_job_push_only_author_posts

### PR DESCRIPTION
**Pull request by stujo**
Make comment_add operation conditional on zendesk_job_push_only_author_posts setting

### CODE REVIEW

**Comment by stujo** [comment]
Not really ready for review I'd just like to get the pipelines running so I can add a spec and check that it passes

**Comment by stujo** [comment]
Thanks @rishabhnambiar ! I'd like to run the workflow again

**Comment by stujo** [comment]
Would love some feedback on this, I think the basics are ready for review

**Comment by stujo** [comment]
The why: We want to sync the posters interactions only to Zendesk so that
- We can focus on solving the poster's issue. 
- We can track our response SLA solely on the original poster's interactions

**Comment by stujo** [comment]
Thank you for your consideration and feedback @scossar much appreciated

**Review by techAPJ — APPROVED** [review]
Looks good. 👍🏼

**Comment by techAPJ** [comment]
Thanks for the detailed specs @stujo 👍🏼

**Comment by stujo** [comment]
Thank you!

**Pull request merged**
