### PR TITLE
Adding sync between zendesk and discourse

### PR DESCRIPTION
**Pull request by smasry**

### CODE REVIEW

**Comment by techAPJ** [comment]
Thanks!

**Comment by techAPJ** [comment]
Hi @smasry, hope you are doing good. 👋 

I have been going through the commits again to cleanup the plugin code, and I can't understand how `zendesk_sync_enabled` setting works.

Do we need to setup anything on Zendesk side to pull/sync comments from Zendesk to Discourse? If so can you expand a bit about how to do that?

In the plugin code it seems like [`discourse_zendesk_plugin/comments#create`](https://github.com/discourse/discourse-zendesk-plugin/blob/master/plugin.rb#L145-L162) method is never used and I am inclined to remove it altogether along with `zendesk_sync_enabled` setting, if it's not being used anywhere.

**Comment by smasry** [comment]
You'd need to setup a Webhook on the Zendesk side.

https://support.zendesk.com/hc/en-us/articles/204890268-Creating-webhooks-with-the-HTTP-target

**Comment by techAPJ** [comment]
I thought of that but what I am confused about is how we will receive `topic_id` as parameter from Zendesk webhook, as [seen here](https://github.com/discourse/discourse-zendesk-plugin/blob/master/plugin.rb#L146).

**Pull request merged**
